### ISSUE TITLE
invalid JA3 reported

### ISSUE THREAD

**Issue by 89z** [scrapfly/python-scrapfly#7] opened 2022-10-29 21:03 UTC
sorry I dont know where to post this, but I noticed that currently these URL:

https://tools.scrapfly.io/api/fp/ja3?extended=1
https://tools.scrapfly.io/api/fp/ja3

are producing invalid JA3. Namely the first value `SSLVersion` can never be 772 or higher

**Comment by 89z** [comment] 2022-11-12 12:03
https://github.com/Danny-Dasilva/CycleTLS/issues/160

**Comment by jjsaunier** [comment] 2022-11-12 18:33
Thanks for reaching out, yes the `SSLVersion` is deprecated from TLS protocol and freeze to avoid BC for any version >=1.3. There is no interest to use this data point in fingerprint since it does not reflect the actual client setting and in the end of the day generates bloated fingerprints, since it's impossible to get back the correct tls version from the fingerprint. 

So I hear the "invalid JA3" but in my/our (scraping) context generating "valid JA3" is in fact useless since it's technically wrong. I can understand it's an issue for people comparing it to ja3er database or such use case but I need to produce accurate data points to reproduce the correct fingerprint. It depends of your usage, to compare with the existing ja3 database, don't use this tool, to reproduce or understand tls client settings or use the fingerprint as input to auto config a client, you can use it. 

I will deprecate the JA3 as soon as the new fingerprinter will be released with more data points (cert compression algo, signature algo, PSK exchange, session_id_length, record_size_limit) seems to be the new standard across major WAF. JA3 is too old (6 years old) and fail the his job to fingerprint modern crypto client. 

I close the issue, the discussion is open

**Closed by jjsaunier** 2022-11-12 18:33 UTC
