### ISSUE TITLE
Unable to execute demo

### ISSUE THREAD

**Issue by DJousto** [scrapfly/python-scrapfly#12] opened 2023-11-20 08:53 UTC
with scrapy 2.11.0 unable to launch anything, demo.py or custom spider will throw errors :

`2023-11-20 09:46:35 [scrapy.core.engine] INFO: Spider opened
2023-11-20 09:46:35 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-11-20 09:46:35 [scrapfly.scrapy.spider] INFO: ==> Retrying request for reason [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('SSL routines', '', 'certificate verify failed')]>]
2023-11-20 09:46:35 [scrapfly.scrapy.spider] WARNING: Retrying <GET https://web-scraping.dev/product/5> for x0: twisted.web._newclient.ResponseNeverReceived
2023-11-20 09:46:35 [scrapfly.scrapy.spider] INFO: ==> Retrying request for reason [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('SSL routines', '', 'certificate verify failed')]>]
2023-11-20 09:46:35 [scrapfly.scrapy.spider] WARNING: Retrying <GET https://web-scraping.dev/product/4> for x0: twisted.web._newclient.ResponseNeverReceived
2023-11-20 09:46:35 [scrapfly.scrapy.spider] INFO: ==> Retrying request for reason [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('SSL routines', '', 'certificate verify failed')]>]
2023-11-20 09:46:35 [scrapfly.scrapy.spider] WARNING: Retrying <GET https://httpbin.dev/status/403> for x0: twisted.web._newclient.ResponseNeverReceived
2023-11-20 09:46:35 [scrapfly.scrapy.spider] INFO: ==> Retrying request for reason [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('SSL routines', '', 'certificate verify failed')]>]
2023-11-20 09:46:35 [scrapfly.scrapy.spider] WARNING: Retrying <GET https://httpbin.dev/status/400> for x0: twisted.web._newclient.ResponseNeverReceived
2023-11-20 09:46:35 [scrapfly.scrapy.spider] INFO: ==> Retrying request for reason [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('SSL routines', '', 'certificate verify failed')]>]
2023-11-20 09:46:35 [scrapfly.scrapy.spider] WARNING: Retrying <GET https://httpbin.dev/status/404> for x0: twisted.web._newclient.ResponseNeverReceived
2023-11-20 09:46:35 [scrapfly.scrapy.spider] INFO: ==> Retrying request for reason [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('SSL routines', '', 'certificate verify failed')]>]
2023-11-20 09:46:35 [scrapfly.scrapy.spider] WARNING: Retrying <GET https://web-scraping.dev/product/1> for x0: twisted.web._newclient.ResponseNeverReceived
2023-11-20 09:46:35 [scrapfly.scrapy.spider] INFO: ==> Retrying request for reason [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('SSL routines', '', 'certificate verify failed')]>]
2023-11-20 09:46:35 [scrapfly.scrapy.spider] WARNING: Retrying <GET https://web-scraping.dev/product/2> for x0: twisted.web._newclient.ResponseNeverReceived
2023-11-20 09:46:35 [scrapfly.scrapy.spider] INFO: ==> Retrying request for reason [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('STORE routines', '', 'unsupported'), ('SSL routines', '', 'certificate verify failed')]>]
2023-11-20 09:46:35 [scrapfly.scrapy.spider] WARNING: Retrying <GET https://web-scraping.dev/product/3> for x0: twisted.web._newclient.ResponseNeverReceived
2023-11-20 09:46:36 [scrapfly] ERROR: [Failure instance: Traceback: <class 'TypeError'>: ExecutionEngine.crawl() takes 2 positional arguments but 3 were given
F:\python310\lib\site-packages\twisted\internet\defer.py:661:callback
F:\python310\lib\site-packages\twisted\internet\defer.py:763:_startRunCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:1750:gotResult
--- <exception caught here> ---
F:\python310\lib\site-packages\twisted\internet\defer.py:1656:_inlineCallbacks
F:\python310\lib\site-packages\twisted\python\failure.py:514:throwExceptionIntoGenerator
F:\python310\lib\site-packages\scrapy\core\downloader\middleware.py:86:process_exception
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\task.py:869:cb
]
2023-11-20 09:46:36 [scrapfly] ERROR: [Failure instance: Traceback: <class 'TypeError'>: ExecutionEngine.crawl() takes 2 positional arguments but 3 were given
F:\python310\lib\site-packages\twisted\internet\defer.py:661:callback
F:\python310\lib\site-packages\twisted\internet\defer.py:763:_startRunCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:1750:gotResult
--- <exception caught here> ---
F:\python310\lib\site-packages\twisted\internet\defer.py:1656:_inlineCallbacks
F:\python310\lib\site-packages\twisted\python\failure.py:514:throwExceptionIntoGenerator
F:\python310\lib\site-packages\scrapy\core\downloader\middleware.py:86:process_exception
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\task.py:869:cb
]
2023-11-20 09:46:36 [scrapfly] ERROR: [Failure instance: Traceback: <class 'TypeError'>: ExecutionEngine.crawl() takes 2 positional arguments but 3 were given
F:\python310\lib\site-packages\twisted\internet\defer.py:661:callback
F:\python310\lib\site-packages\twisted\internet\defer.py:763:_startRunCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:1750:gotResult
--- <exception caught here> ---
F:\python310\lib\site-packages\twisted\internet\defer.py:1656:_inlineCallbacks
F:\python310\lib\site-packages\twisted\python\failure.py:514:throwExceptionIntoGenerator
F:\python310\lib\site-packages\scrapy\core\downloader\middleware.py:86:process_exception
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\task.py:869:cb
]
2023-11-20 09:46:36 [scrapfly] ERROR: [Failure instance: Traceback: <class 'TypeError'>: ExecutionEngine.crawl() takes 2 positional arguments but 3 were given
F:\python310\lib\site-packages\twisted\internet\defer.py:661:callback
F:\python310\lib\site-packages\twisted\internet\defer.py:763:_startRunCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:1750:gotResult
--- <exception caught here> ---
F:\python310\lib\site-packages\twisted\internet\defer.py:1656:_inlineCallbacks
F:\python310\lib\site-packages\twisted\python\failure.py:514:throwExceptionIntoGenerator
F:\python310\lib\site-packages\scrapy\core\downloader\middleware.py:86:process_exception
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\task.py:869:cb
]
2023-11-20 09:46:36 [scrapfly] ERROR: [Failure instance: Traceback: <class 'TypeError'>: ExecutionEngine.crawl() takes 2 positional arguments but 3 were given
F:\python310\lib\site-packages\twisted\internet\defer.py:661:callback
F:\python310\lib\site-packages\twisted\internet\defer.py:763:_startRunCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:1750:gotResult
--- <exception caught here> ---
F:\python310\lib\site-packages\twisted\internet\defer.py:1656:_inlineCallbacks
F:\python310\lib\site-packages\twisted\python\failure.py:514:throwExceptionIntoGenerator
F:\python310\lib\site-packages\scrapy\core\downloader\middleware.py:86:process_exception
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\task.py:869:cb
]
2023-11-20 09:46:36 [scrapfly] ERROR: [Failure instance: Traceback: <class 'TypeError'>: ExecutionEngine.crawl() takes 2 positional arguments but 3 were given
F:\python310\lib\site-packages\twisted\internet\defer.py:661:callback
F:\python310\lib\site-packages\twisted\internet\defer.py:763:_startRunCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:1750:gotResult
--- <exception caught here> ---
F:\python310\lib\site-packages\twisted\internet\defer.py:1656:_inlineCallbacks
F:\python310\lib\site-packages\twisted\python\failure.py:514:throwExceptionIntoGenerator
F:\python310\lib\site-packages\scrapy\core\downloader\middleware.py:86:process_exception
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\task.py:869:cb
]
2023-11-20 09:46:36 [scrapfly] ERROR: [Failure instance: Traceback: <class 'TypeError'>: ExecutionEngine.crawl() takes 2 positional arguments but 3 were given
F:\python310\lib\site-packages\twisted\internet\defer.py:661:callback
F:\python310\lib\site-packages\twisted\internet\defer.py:763:_startRunCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:1750:gotResult
--- <exception caught here> ---
F:\python310\lib\site-packages\twisted\internet\defer.py:1656:_inlineCallbacks
F:\python310\lib\site-packages\twisted\python\failure.py:514:throwExceptionIntoGenerator
F:\python310\lib\site-packages\scrapy\core\downloader\middleware.py:86:process_exception
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\task.py:869:cb
]
2023-11-20 09:46:36 [scrapfly] ERROR: [Failure instance: Traceback: <class 'TypeError'>: ExecutionEngine.crawl() takes 2 positional arguments but 3 were given
F:\python310\lib\site-packages\twisted\internet\defer.py:661:callback
F:\python310\lib\site-packages\twisted\internet\defer.py:763:_startRunCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\defer.py:1750:gotResult
--- <exception caught here> ---
F:\python310\lib\site-packages\twisted\internet\defer.py:1656:_inlineCallbacks
F:\python310\lib\site-packages\twisted\python\failure.py:514:throwExceptionIntoGenerator
F:\python310\lib\site-packages\scrapy\core\downloader\middleware.py:86:process_exception
F:\python310\lib\site-packages\twisted\internet\defer.py:857:_runCallbacks
F:\python310\lib\site-packages\twisted\internet\task.py:869:cb
]`

**Comment by Granitosaurus** [comment] 2023-12-21 16:04
This seems like scrapy SSL dependancy issue. See scrapy install instructions related to openssl https://docs.scrapy.org/en/latest/intro/install.html 

The other error is duplicate of #11 and is resolved in the commit that closed it.

**Closed as completed by Granitosaurus** 2023-12-21 16:04 UTC
